SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
--The solution:
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION
	SELECT * FROM Exercise WHERE ExerciseID = 1;
COMMIT TRANSACTION
GO

