ALTER DATABASE Fitness_Guide
SET ALLOW_SNAPSHOT_ISOLATION ON;

BEGIN TRAN
	WAITFOR DELAY '00:00:05';
	UPDATE Exercise SET Orientation = 'Vertical' WHERE ExerciseID = 1;
	WAITFOR DELAY '00:00:05';

COMMIT TRAN;