package application;

import javafx.fxml.FXML;

import javafx.scene.text.Text;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class Ex2Controller {
	@FXML
	private PasswordField passwordField;
	@FXML
	private Text actionTarget;
	
	 @FXML
	 private Text welcomeText;

	// Event Listener on Button.onAction
	@FXML
	public void handleSubmitButtonAction(ActionEvent event) {
		// TODO Autogenerated
		actionTarget.setText("Sign in button pressed");
	}
}
