
--The solution:
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRAN
	SELECT * FROM Exercise WHERE ExerciseID = 1;
	WAITFOR DELAY '00:00:10';
	SELECT * FROM Exercise WHERE ExerciseID = 1;
COMMIT TRAN